# Generated by Django 6.1.1 on 2026-09-29 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('token_number', models.CharField(max_length=80, unique=True)),
                ('inputs', models.JSONField()),
                ('state', models.CharField(default='PENDING', max_length=12)),
                ('qr_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
